apiVersion: v1
kind: Service
metadata:
  name: service-goreplay
spec:
  selector:
    app: goreplay-app
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: server-port
      protocol: TCP
  type: NodePort